<html>
                <head>
                <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
                <title>067 Solution raising our own custom error</title>
                </head>
                <body>
                <div class="container">
                <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <p class="lead"><p>Welcome back to another coding exercise solution!</p>

<p>This is my solution to the coding exercise. Again, it may be slightly different from yours!</p>





<pre class="prettyprint linenums"># - define a UncountableError that takes in wrong_value as the only argument
# - the UncountableError should inherit ValueError
# - the UncountableError should indicate an error message like this:
#    'Invalid valid for n, WRONG_VALUE. n must be greater than 0.'
#    where WRONG_VALUE should be replaced by the given value in the argument
# define your UncountableError here:

class UncountableError(ValueError):
    def __init__(self, wrong_value):
        super().__init__('Invalid valid for n, {}. n must be greater than 0.'.format(wrong_value))

# do not change anything in the count_from_zero_to_n() function
# you may expect your UncountableError work in the following way
def count_from_zero_to_n(n):
    if n &lt; 1:
        raise UncountableError(n)
    for x in range(0, n + 1):
        print(x)</pre>



<p>Let me know how you got on!</p>







<p>Kind regards,</p>





<p>â€” Jose and the Teclado team</p></p>
                </div>
                </div>
                </div>
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
                </body>
                </html>